name: danger

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20.x
        uses: actions/setup-node@master
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm ci
      - name: Danger
        run: npm danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
