name: Tests

on: [ push,pull_request ]

jobs:
  build:
    name: Test Suite
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint code
        run: npm run lint

      - name: Run test suite
        run: npm test
